### ISSUE TITLE
Add sitemap

### ISSUE THREAD

**Issue by da-kami** [get10101/10101.github.io#4]
Currently 10101.finance cannot be found on search engines. 

There are multiple things that can be tackled, adding a sitemap is a good start.

check this out: 

https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap
https://blog.hubspot.com/marketing/build-sitemap-website

**Comment by bonomat** [comment]
Resolved. The page is now being indexed by google.

**Comment by bonomat** [comment]
> Did we actually add a sitemap? Besides the page being indexed now, the sitemap can also help with ranking it as far as I understand.

No we did not. A sidemap is only required if you have multiple urls which are not being indexed correctly.
