### ISSUE TITLE
Homepage website : FAQ LINK BROKEN (404)

### ISSUE THREAD

**Issue by Science-G** [get10101/10101.github.io#60]
The link on the homepage (index.html) of https://10101.finance leads to 404:
![Capture d’écran 2024-01-31 à 20 31 44](https://github.com/get10101/10101.github.io/assets/137571657/f14ed2b7-8154-4985-8770-9a3e879cb583)

If I explore the index.html file, it seems clear that the target of the link leads to "#" (top of the blog page?)
![Capture d’écran 2024-01-31 à 20 33 04](https://github.com/get10101/10101.github.io/assets/137571657/5434abfc-a67c-4488-9edb-fb3ec04c867a)

----

**first fix proposed :** replace the "#" by "https://10101.finance/blog/faq" // (edited)
I prepared this PR if we choose that solution: https://github.com/get10101/10101.github.io/pull/59

----

**Alternative fix proposed :** move the FAQ at the top of the blog topics (like before 2024 vision) by changing is name for :
![Capture d’écran 2024-01-31 à 20 37 46](https://github.com/get10101/10101.github.io/assets/137571657/84734ff2-cae6-4e21-b4a4-1d1f2e985a67)

Solution : changing the name for "2024-02-01-FAQ.md"
⚠️ If we chose this solution, we would have to update the FAQ name **every time**

Or, find a way to tweak the blog app to "pin" it to the top regardless of the date included in the name 🤷‍♂️

**Comment by bonomat** [comment]
I guess what we want is to have 10101.finance/faq
