### ISSUE TITLE
Add FAQ to the homepage

### ISSUE THREAD

**Issue by da-kami** [get10101/10101.github.io#8]
We should add a FAQ to the homepage to make it easier for user to get answers to common questions such as:

* What is a "DLC" and how does it work? 
    * A simple description and a link to the blogpost where we go into detail how it works in 10101. 

* What makes 10101 more secure than other solutions? 
    * A summary of self-custodial and what is means and a link to our USP blogpost (not published as of writing this) 

* Do I have to trust the Oracle?
    * A simple explanation of what the oracle does link to DLCs and our vision for evolving the Oracle.

Feel free to add more common questions in comments!

**Comment by bonomat** [comment]
A few which come to mind: 

- How do I become a beta user? 
	- https://notionforms.io/forms/10101-beta-signup
- Where can I download the app ? 
	- (once we have a link)
- What tech is 10101 built on?
	- rust-lightning, rust-dlc, our repos
- Who are you? 
	- We should add a team page!
- How do I back-up my wallet?
	- LoremLipsum
